### ISSUE TITLE
Problem with ASTTransformation and Compile Order

### ISSUE THREAD

**Issue by ManOki** [9ci/grails-audit-trail#18]
I've tried very hardly to set the type of createdBy and editedBy to my specific domain class "User"...

But the setting works only with the right compile order. If you reference to an class that don't exist while compiling a class with @gorm.AuditStamp, you might get compile error.

```java
createdBy.type = "security.User" // error, class is not available
createdBy.type = security.User.class.name  // no error, but defaults to Long

@see gorm.FieldProps:36
```

Is there any solution, without using a precompiled class from another plugin or manual double compiling (without and with annotation) etc.?
(If there isn't a hint in the documentation might be helpful for others)

Thanks

**Comment by basejump** [comment]
is this still an issue? if you have a work around please submit an update to the README with what you did
