### ISSUE TITLE
upgrade to new grails 2.4

### ISSUE THREAD

**Issue by basejump** [9ci/grails-audit-trail#30]

**Comment by sebDK** [comment]
Hi there,

Are there any news about grails-audit-trail on grails 2,4?

BR,

Sébastien

**Comment by sebDK** [comment]
Basically, it looks it is just needed to change def loadAfter = ['hibernate'] to def loadAfter = ['hibernate4'] in AuditTrailGrailsPlugin.groovy.

S.

**Comment by basejump** [comment]
will push new release
