### ISSUE TITLE
Migration to Grails 3

### ISSUE THREAD

**Issue by sebDK** [9ci/grails-audit-trail#34]
Hi there,
This plugin is really useful.
Is there any plan to migrat to Grails 3?

S.

**Comment by Kanishkaz** [comment]
We use this plugin in Grails 2.x and are looking to upgrade to Grails 3.x.
It would be great if this plugin could be upgraded to support Grails 3.

**Comment by jdabal** [comment]
We don't plan to upgrade yet. We're open if you want to do it.
